"""Abstract interfaces for data repository adapters."""

from typing import Protocol

from app.domain.entities.document import Chunk, Document, DocumentStatus, Section
from app.domain.entities.user import User


class AbstractDocumentRepository(Protocol):
    async def find_by_id(self, doc_id: str) -> Document | None: ...
    async def find_by_ids(self, doc_ids: list[str]) -> list[Document]: ...
    async def save(self, document: Document) -> Document: ...
    async def update_status(self, doc_id: str, status: DocumentStatus, error_msg: str = "") -> None: ...
    async def delete(self, doc_id: str) -> None: ...
    async def list_all(self, tenant_id: str, limit: int = 50, offset: int = 0) -> list[Document]: ...
    async def count_by_tenant(self, tenant_id: str) -> int: ...


class AbstractChunkRepository(Protocol):
    async def save_batch(self, chunks: list[Chunk]) -> list[Chunk]: ...
    async def find_by_doc_id(self, doc_id: str) -> list[Chunk]: ...
    async def delete_by_doc_id(self, doc_id: str) -> None: ...
    async def find_by_ids(self, chunk_ids: list[str]) -> list[Chunk]: ...
    async def find_by_section_id(self, section_id: str) -> list[Chunk]: ...
    async def find_prev_chunk(self, chunk_id: str) -> Chunk | None: ...
    async def find_next_chunk(self, chunk_id: str) -> Chunk | None: ...
    async def find_parent_chunk(self, chunk_id: str) -> Chunk | None: ...


class AbstractSectionRepository(Protocol):
    async def save_batch(self, sections: list[Section]) -> list[Section]: ...
    async def find_by_doc_id(self, doc_id: str) -> list[Section]: ...
    async def find_by_id(self, section_id: str) -> Section | None: ...
    async def delete_by_doc_id(self, doc_id: str) -> None: ...
    async def find_children(self, parent_section_id: str) -> list[Section]: ...
    async def find_roots(self, doc_id: str) -> list[Section]: ...


class AbstractUserRepository(Protocol):
    async def find_by_id(self, user_id: str) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def find_by_api_key_hash(self, key_hash: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def list_all(self, tenant_id: str, limit: int = 50, offset: int = 0) -> list[User]: ...
    async def count_all(self, tenant_id: str) -> int: ...
